package com.dagger2.zeroscreen.mvp.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dagger2.zeroscreen.mvp.model.db.CardInfo;

import com.dagger2.zeroscreen.mvp.model.db.CardInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardInfoDaoConfig;

    private final CardInfoDao cardInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardInfoDaoConfig = daoConfigMap.get(CardInfoDao.class).clone();
        cardInfoDaoConfig.initIdentityScope(type);

        cardInfoDao = new CardInfoDao(cardInfoDaoConfig, this);

        registerDao(CardInfo.class, cardInfoDao);
    }
    
    public void clear() {
        cardInfoDaoConfig.getIdentityScope().clear();
    }

    public CardInfoDao getCardInfoDao() {
        return cardInfoDao;
    }

}
